CREATE DATABASE IF NOT EXISTS db_sample;
USE db_sample;

CREATE TABLE IF NOT EXISTS test(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    text TEXT
);

CREATE TABLE IF NOT EXISTS products(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    product TEXT NOT NULL
);
